### ISSUE TITLE
dev broker does not start

### ISSUE THREAD

**Issue by jnehring** [dkt-projekt/DktBrokerStandalone#6]
Today the document collection service lost the database collection. So I added these lines to the configuration:

```
spring.datasource.testOnBorrow=true
spring.datasource.validationQuery=SELECT 1
```

We had a similar problem in FREME and this configuration solved the problem.

Now the broker does not start. I think the problem does not originate from my config change because the error message is

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.dkt.eservices.esentimentanalysis.dfki.SentimentAnalyzer]: Constructor threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1092)
        ... 23 more
Caused by: java.lang.NullPointerException
        at de.dkt.eservices.esentimentanalysis.dfki.SentimentAnalyzer.<init>(SentimentAnalyzer.java:45)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
```

@PeterBourgonje any idea whats wrong?

**Comment by PeterBourgonje** [comment]
fixed (issue with autowiring of sentiment analyzer setting, thanks @jmschnei )
